version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    image: levinsonvaleri/portfolio_frontend:latest
    platform: "linux/amd64"
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: levinsonvaleri/portfolio_backend:latest
    platform: "linux/amd64"

    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

